// Code generated by hz-openapi-gen. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	"example.com/service/biz/handler"
)

func GeneratedRegister(h *server.Hertz) {
	h.GET("/health", handler.GetHealth)
	h.GET("/users", handler.ListUsers)
	h.POST("/users", handler.CreateUser)
	h.GET("/users/:id", handler.GetUserByID)
}
