// Code generated by hz-openapi-gen. DO NOT EDIT.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"

	"example.com/service/biz/opid"
	public "example.com/service/internal/public"
)

// GetHealth handles GET /health.
// Health check
// @router /health [GET]
func GetHealth(ctx context.Context, c *app.RequestContext) {
	// delegated
	public.Serve(ctx, c, opid.GetHealth)
}
