// Code generated by hz-openapi-gen. DO NOT EDIT.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"

	"example.com/service/biz/opid"
	public "example.com/service/internal/public"
)

// ListUsers handles GET /users.
// List users
// @router /users [GET]
func ListUsers(ctx context.Context, c *app.RequestContext) {
	// delegated
	public.Serve(ctx, c, opid.ListUsers)
}

// CreateUser handles POST /users.
// Create a new user
// @router /users [POST]
func CreateUser(ctx context.Context, c *app.RequestContext) {
	// delegated
	public.Serve(ctx, c, opid.CreateUser)
}

// GetUserByID handles GET /users/{id}.
// Get user by ID
// @router /users/{id} [GET]
func GetUserByID(ctx context.Context, c *app.RequestContext) {
	// delegated
	public.Serve(ctx, c, opid.GetUserByID)
}
