// Code generated by hz-openapi-gen.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetHealth handles GET /health.
// Health check
// @router /health [GET]
func GetHealth(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusNotImplemented, map[string]string{"error": "not implemented"})
}
