// Code generated by hz-openapi-gen.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	"example.com/service/biz/model"
)

// ListUsers handles GET /users.
// List users
// @router /users [GET]
func ListUsers(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusNotImplemented, map[string]string{"error": "not implemented"})
}

// CreateUser handles POST /users.
// Create a new user
// @router /users [POST]
func CreateUser(ctx context.Context, c *app.RequestContext) {
	var req model.CreateUserRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": err.Error()})
		return
	}

	c.JSON(consts.StatusNotImplemented, map[string]string{"error": "not implemented"})
}

// GetUserByID handles GET /users/{id}.
// Get user by ID
// @router /users/{id} [GET]
func GetUserByID(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusNotImplemented, map[string]string{"error": "not implemented"})
}
