package generator

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/victorzhuk/hz-openapi-gen/internal/hzutil"
	"github.com/victorzhuk/hz-openapi-gen/internal/openapi"
)

const GeneratedMarker = "// Code generated by hz-openapi-gen."
const DoNotEditMarker = GeneratedMarker + " DO NOT EDIT."

func jsonTag(f openapi.FieldDef) string {
	if f.Required {
		return fmt.Sprintf("json:%q", f.JSONName)
	}
	return fmt.Sprintf("json:%q", f.JSONName+",omitempty")
}

var tmpl = template.Must(template.New("hz").Funcs(template.FuncMap{
	"jsonTag": jsonTag,
}).Parse(routerTmpl + handlerTmpl + handlerFuncTmpl + modelTmpl + mainTmpl + generateTmpl))

const routerTmpl = `
{{define "router"}}` + DoNotEditMarker + `

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	"{{.HandlerImport}}"
)

func GeneratedRegister(h *server.Hertz) {
{{- range .Routes}}
	{{.Stmt}}
{{- end}}
}
{{end}}`

const handlerTmpl = `
{{define "handler"}}` + GeneratedMarker + `

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
{{- if .NeedModel}}

	"{{.ModelImport}}"
{{- end}}
)
{{range .Handlers}}
// {{.FuncName}} handles {{.Method}} {{.OpenAPIPath}}.
{{- if .Summary}}
// {{.Summary}}
{{- end}}
// @router {{.OpenAPIPath}} [{{.Method}}]
func {{.FuncName}}(ctx context.Context, c *app.RequestContext) {
{{- if .RequestModel}}
	var req model.{{.RequestModel}}
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": err.Error()})
		return
	}
{{end}}
	c.JSON(consts.StatusNotImplemented, map[string]string{"error": "not implemented"})
}
{{end}}
{{end}}`

const handlerFuncTmpl = `
{{define "handlerFunc"}}// {{.FuncName}} handles {{.Method}} {{.OpenAPIPath}}.
{{- if .Summary}}
// {{.Summary}}
{{- end}}
// @router {{.OpenAPIPath}} [{{.Method}}]
func {{.FuncName}}(ctx context.Context, c *app.RequestContext) {
{{- if .RequestModel}}
	var req model.{{.RequestModel}}
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, map[string]string{"error": err.Error()})
		return
	}
{{end}}
	c.JSON(consts.StatusNotImplemented, map[string]string{"error": "not implemented"})
}
{{end}}`

const modelTmpl = `
{{define "model"}}` + DoNotEditMarker + `

package model
{{if .NeedTime}}
import "time"
{{end}}
{{- with .Model}}
{{- if .Description}}
// {{.Name}} {{.Description}}
{{- end}}
type {{.Name}} struct {
{{- range .Fields}}
	{{.Name}} {{.GoType}} ` + "`{{jsonTag .}}`" + `
{{- end}}
}
{{- end}}
{{end}}`

const mainTmpl = `
{{define "main"}}package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	"{{.RouterImport}}"
)

func main() {
	h := server.Default(server.WithHostPorts(":8888"))
	router.GeneratedRegister(h)
	h.Spin()
}
{{end}}`

const generateTmpl = `
{{define "generate"}}//go:build ignore

package main

//go:generate go run {{.GenModule}}/cmd/hz-openapi-gen -spec={{.SpecPath}} -out=. -module={{.Module}}

func main() {}
{{end}}`

func render(name string, data any) ([]byte, error) {
	var buf bytes.Buffer
	if err := tmpl.ExecuteTemplate(&buf, name, data); err != nil {
		return nil, fmt.Errorf("render %s: %w", name, err)
	}
	formatted, err := hzutil.FormatGo(name+".go", buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format %s: %w", name+".go", err)
	}
	return formatted, nil
}

func renderHandlerFunc(data any) ([]byte, error) {
	var buf bytes.Buffer
	if err := tmpl.ExecuteTemplate(&buf, "handlerFunc", data); err != nil {
		return nil, fmt.Errorf("render handlerFunc: %w", err)
	}
	return buf.Bytes(), nil
}
